name: sulu_mobile_application
description: SULU mobile app with flutter

publish_to: 'none' 

version: 1.0.7+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pinput: ^1.2.2
  google_fonts: 2.2.0
  carousel_slider: ^4.0.0
  flutter_bloc: ^8.0.0
  flutter_secure_storage: ^5.0.2
  table_calendar: ^3.0.3
  url_launcher: ^6.0.18
  pull_to_refresh: ^2.0.0
  share: ^2.0.4
  image_picker: ^0.8.4+4
  dio: ^4.0.4
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  chips_choice: ^2.0.1
  rename: ^2.0.1
  cached_network_image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"


flutter:

  uses-material-design: true

  assets:
    - assets/background/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/images/services/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"